/*
 * FoodPlanItemSummaryJPanel.java
 *
 * Created on September 18, 2006, 2:26 PM
 */

package foodthinger;

/**
 *
 * @author  RC Stanley
 */
public class FoodPlanItemSummaryJPanel extends javax.swing.JPanel
{
    java.util.Vector summaries;
    java.util.HashMap id2Cannery;
    java.util.HashMap id2Units;
    int numYears;
    /** Creates new form FoodPlanItemSummaryJPanel */
    public FoodPlanItemSummaryJPanel(java.util.Vector data, java.util.HashMap id2Cannery, java.util.HashMap id2Units)
    {
	summaries = new java.util.Vector();
	this.id2Cannery = id2Cannery;
	this.id2Units = id2Units;
	this.numYears = numYears;
	initComponents();
	//createSummaries(data);
	
    }
    
    /**
     * add the item to the correct category summary
     */
    void addItem(FoodPlanItem fpi)
    {
	for(int i = 0; i<summaries.size();i++)
	{
	    FoodPlanSummaryItem fsi = (FoodPlanSummaryItem)summaries.get(i);
	    if(fsi.addFoodItem(fpi)) return;
	}
	FoodPlanSummaryItem fsi = new FoodPlanSummaryItem(fpi.cannery_cat,(String)(this.id2Cannery.get(String.valueOf(fpi.cannery_cat))), new javax.swing.JLabel(), fpi.recommendedAmountUnits, (String)(this.id2Units.get(String.valueOf(fpi.recommendedAmountUnits))));
	fsi.addFoodItem(fpi);
	summaries.add(fsi);
	add(fsi.text);
    }
    
    void createSummaries(java.util.Vector data,int numYears)
    {
	this.jLabelNumYears.setText( this.jLabelNumYears.getText()+String.valueOf(numYears));
	int k = data.size();
	for(int i = 0; i<data.size();i++)
	{
	    Object o = data.get(i);
	    if(o!=null && o instanceof FoodPlanItem)
	    {
		FoodPlanItem fpi = (FoodPlanItem) o;
		addItem(fpi);
	    }
	}
	
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        jLabel1 = new javax.swing.JLabel();
        jLabelNumYears = new javax.swing.JLabel();

        setLayout(new java.awt.GridLayout(7, 0));

        setMinimumSize(new java.awt.Dimension(122, 84));
        jLabel1.setText("Summary: (Needed/User)");
        add(jLabel1);

        jLabelNumYears.setText("Number of Months:");
        add(jLabelNumYears);

    }
    // </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelNumYears;
    // End of variables declaration//GEN-END:variables
    
}
