/*
 * OptionJPanel.java
 *
 * Created on July 31, 2006, 9:27 PM
 */

package foodthinger;

/**
 *
 * @author  RC Stanley
 */
public class OptionJPanel extends javax.swing.JPanel
{
    FoodModel fm;
    String existsQuery;
    String deleteQuery;
    String insertQuery;
    String updateQuery;
    String countQuery;
    String comboBoxQuery;
    String table;
    int idIndex;
    int dataIndex;
    /** Creates new form OptionJPanel */
    public OptionJPanel(FoodModel fm, String table, String existsQuery,
	String deleteQuery,
	String insertQuery,
	String updateQuery,
	String countQuery,
	String comboBoxQuery, int idIndex, int dataIndex)
    {
	this.fm = fm;
	this.table = table;
	this.existsQuery=existsQuery;
	this.deleteQuery=deleteQuery;
	this.insertQuery=insertQuery;
	this.updateQuery=updateQuery;
	this.countQuery=countQuery;
	this.comboBoxQuery = comboBoxQuery;
	this.idIndex = idIndex;
	this.dataIndex = dataIndex;
	initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        java.awt.GridBagConstraints gridBagConstraints;

        jButtonDelete = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButtonAdd = new javax.swing.JButton();
        jButtonRename = new javax.swing.JButton();
        jButtonOK = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();

        setLayout(new java.awt.GridBagLayout());

        jButtonDelete.setMnemonic('d');
        jButtonDelete.setText("Delete");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonDeleteActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        add(jButtonDelete, gridBagConstraints);

        jTextField1.setMinimumSize(new java.awt.Dimension(59, 20));
        jTextField1.setPreferredSize(new java.awt.Dimension(100, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 7, 0);
        add(jTextField1, gridBagConstraints);

        jButtonAdd.setMnemonic('a');
        jButtonAdd.setText("<- Add");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonAddActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 6, 0);
        add(jButtonAdd, gridBagConstraints);

        jButtonRename.setMnemonic('r');
        jButtonRename.setText("<- Rename");
        jButtonRename.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonRenameActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 6, 0);
        add(jButtonRename, gridBagConstraints);

        jButtonOK.setMnemonic('o');
        jButtonOK.setText("OK");
        jButtonOK.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonOKActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        add(jButtonOK, gridBagConstraints);

        jComboBox1.setModel(fm.getComboModelForQuery(comboBoxQuery,idIndex,dataIndex));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        add(jComboBox1, gridBagConstraints);

    }
    // </editor-fold>//GEN-END:initComponents
    java.awt.Component getSubWindow(java.awt.Component child)
    {
	
	java.awt.Component next = child.getParent();
	java.awt.Component oldNext = child;
	//go up the tree until you find the window to close
	while(true)
	{
	    if(next == null) return null;
	    if(next == oldNext) return null;
	    if(next instanceof OptionsJInternalFrame)
	    {
		return next;
	    }
	    oldNext = next;
	    next = next.getParent();
	}
	//return null;
    }
    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonOKActionPerformed
    {//GEN-HEADEREND:event_jButtonOKActionPerformed
	//hack need to do this for real to close the window
	java.awt.Component window = getSubWindow(this);
	if(window!=null)
	{
	    window.setVisible(false);
	}
	
	//clear text box
	this.jTextField1.setText("");
    }//GEN-LAST:event_jButtonOKActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonAddActionPerformed
    {//GEN-HEADEREND:event_jButtonAddActionPerformed
//get the text from the text box
	String text = this.jTextField1.getText();
	text = text.trim();
	//if it is null or in use then throw a fit
	if(text.length() == 0)
	{
	    javax.swing.JOptionPane.showMessageDialog(this,Constants.ERROR_ADDING,Constants.ERROR,javax.swing.JOptionPane.ERROR_MESSAGE);
	    return;
	}
	int count = fm.exists(/*Constants.CHECK_STORE*/existsQuery, new String[]{text},0);
	if(count > 0)
	{
	    javax.swing.JOptionPane.showMessageDialog(this,text+" "+Constants.ERROR_ADDING_EXISTS,Constants.ERROR,javax.swing.JOptionPane.ERROR_MESSAGE);
	    return;
	}
	//otherwise add it to the db
	String err = fm.exec(/*Constants.INSERT_STORE*/insertQuery, new String[]{text},table);
	if(err == null || err.length()==0)
	{
	    javax.swing.JOptionPane.showMessageDialog(this,Constants.SUCCESS_INSERTING_REAL+" "+text,Constants.SUCCESS_INSERTING_REAL,javax.swing.JOptionPane.INFORMATION_MESSAGE);
	}
	else
	{
	    javax.swing.JOptionPane.showMessageDialog(this,Constants.ERROR_INSERTING_REAL+" "+text+" "+err,Constants.ERROR,javax.swing.JOptionPane.ERROR_MESSAGE);
	}
	//warn all the associated models to update themselves
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonRenameActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonRenameActionPerformed
    {//GEN-HEADEREND:event_jButtonRenameActionPerformed
//get the text from the text box
	String text = this.jTextField1.getText();
	text = text.trim();
	//if it is null or in use then throw a fit
	if(text.length() == 0)
	{
	    javax.swing.JOptionPane.showMessageDialog(this,Constants.ERROR_ADDING,Constants.ERROR,javax.swing.JOptionPane.ERROR_MESSAGE);
	    return;
	}
	FoodTreeNode node = (FoodTreeNode)this.jComboBox1.getSelectedItem();
	//error out, no nodes
	if(node == null)
	{
	    javax.swing.JOptionPane.showMessageDialog(this,Constants.ERROR_ADDING,Constants.ERROR,javax.swing.JOptionPane.ERROR_MESSAGE);
	    return;
	}
	String id = String.valueOf(node.getId());
	int count = fm.exists(/*Constants.CHECK_STORE*/existsQuery, new String[]{text},0);
	if(count > 0)
	{
	    javax.swing.JOptionPane.showMessageDialog(this,text+" "+Constants.ERROR_UPDATE,Constants.ERROR,javax.swing.JOptionPane.ERROR_MESSAGE);
	    return;
	}
	//otherwise add it to the db
	
	String err = fm.exec(/*Constants.UPDATE_STORE*/updateQuery, new String[]{text,id},table);
	if(err == null || err.length()==0)
	{
	    javax.swing.JOptionPane.showMessageDialog(this,Constants.SUCCESS_UPDATE+" "+text,Constants.SUCCESS_UPDATE,javax.swing.JOptionPane.INFORMATION_MESSAGE);
	}
	else
	{
	    javax.swing.JOptionPane.showMessageDialog(this,Constants.ERROR_UPDATE+" "+text+" "+err,Constants.ERROR,javax.swing.JOptionPane.ERROR_MESSAGE);
	}
	//warn all the associated models to update themselves
    }//GEN-LAST:event_jButtonRenameActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonDeleteActionPerformed
    {//GEN-HEADEREND:event_jButtonDeleteActionPerformed
//check and see if in use
	FoodTreeNode node = (FoodTreeNode)this.jComboBox1.getSelectedItem();
	if(node == null)
	{
	    javax.swing.JOptionPane.showMessageDialog(this,Constants.ERROR_DELETING,Constants.ERROR,javax.swing.JOptionPane.ERROR_MESSAGE);
	    return;
	}
	String id = String.valueOf(node.getId());
	int count = fm.exists(/*Constants.CHECK_STORE_IN_FOOD_STORED*/countQuery, new String[]{id},0);
	if(count > 0)
	{
	    javax.swing.JOptionPane.showMessageDialog(this,Constants.ERROR_DELETING+ " "+node.getCategory()+". "+String.valueOf(count)+Constants.ERROR_DELETING_INUSE
		    ,Constants.ERROR,javax.swing.JOptionPane.ERROR_MESSAGE);
	    return;
	}
	//not in use, so delete
	String err = fm.exec(/*Constants.DELETE_STORE*/deleteQuery, new String[]{id},table);
	if(err == null || err.length()==0)
	{
	    javax.swing.JOptionPane.showMessageDialog(this,Constants.SUCCESS_DELETING+" "+node.getCategory(),Constants.SUCCESS_DELETING,javax.swing.JOptionPane.INFORMATION_MESSAGE);
	}
	else
	{
	    javax.swing.JOptionPane.showMessageDialog(this,Constants.ERROR_DELETING+" "+node.getCategory()+" "+err,Constants.ERROR,javax.swing.JOptionPane.ERROR_MESSAGE);
	}
    }//GEN-LAST:event_jButtonDeleteActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JButton jButtonRename;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
    
}
